### ISSUE TITLE
Real Time Speech to text conversation

### ISSUE THREAD

**Issue by surendransuri** [google-gemini/cookbook#105]
### Description of the feature request:

Hi, I want to use Gemini 1.5 Pro's newest multi-model. I'm looking for a feature similar to what's in Vertex AI playground, where we can convert speech to text in real-time. Right now, In this Gemini API examples we see that inferencing does this in batches after uploading a file, but I need it to happen in real-time. Can you help me figure out how to do this? Thanks a lot!

**Comment by random-forests** [comment]
Hi surendransuri, thanks for your question. Google AI Studio and the Gemini API do not support audio streaming right now. You can ask more about the best ways to work with audio on https://discuss.ai.google.dev/.

**Comment by rflpsz** [comment]
you can just use speechSynthesis from Google Chrome native API.
