### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by akbarjorayev** [google-gemini/cookbook#106]
### Description of the feature request:

![Screenshot_20240503_203504_Chrome](https://github.com/google-gemini/cookbook/assets/100585930/3bee9522-cd60-4059-8b79-fd4007b8808f)
Make these code colorful and more readable (word wrap for small screens)

### What problem are you trying to solve with this feature?

Better understanding

**Comment by singhniraj08** [comment]
@akbarjorayev,
Thank you reporting this issue. 
This repository is for issues related to guides and examples for the Gemini API. For issues related to Docs, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by akbarjorayev** [comment]
> @akbarjorayev, Thank you reporting this issue. This repository is for issues related to guides and examples for the Gemini API. For issues related to Docs, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below.
> 
> ![image](https://private-user-images.githubusercontent.com/110809167/318350067-7d11fa96-c1dc-45eb-bb7c-ec8d6609c383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODYzODMsIm5iZiI6MTcxNDk4NjA4MywicGF0aCI6Ii8xMTA4MDkxNjcvMzE4MzUwMDY3LTdkMTFmYTk2LWMxZGMtNDVlYi1iYjdjLWVjOGQ2NjA5YzM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwOTAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTlmZTQ5N2MxMWI4OTgyYzAzZTE2ZmI3YzVkODRmMjhlOGExNjMyZGFiODJhMmYwZjA1MTlmOTI0NjAyNzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.trbWp06It_2d6Ac7XjI0X5vC4-CHhrRvF2AE8GimGrw)

Thanks @singhniraj08

**Comment by akbarjorayev** [comment]
I will close this issue
