### ISSUE TITLE
make code-only version of notebooks available

### ISSUE THREAD

**Issue by fredzannarbor** [google-gemini/cookbook#107]
### Description of the feature request:

The example notebooks are great, but if, like me, you are not big into notebooks, you may want to be able to just extract the code without all the explanatory Javascript.  Another folder with "code-only examples" would do the trick.

### What problem are you trying to solve with this feature?

ease of access to code samples

### Any other information you'd like to share?

Mentioned this to @logankilpatrick who liked idea.

**Comment by markmcd** [comment]
We've added some standalone samples to the various SDK repositories, is this sufficient for what you're asking?

e.g. for Python & REST: https://github.com/google-gemini/generative-ai-python/tree/main/samples

**Comment by fredzannarbor** [comment]
Yes, those are great. Copypasta dreaming!
