### ISSUE TITLE
Broken Links on website

### ISSUE THREAD

**Issue by quick007** [google-gemini/cookbook#137]
### Description of the bug:

If you go to [the cookbook page](https://ai.google.dev/gemini-api/cookbook) on the website, many (if not all) lead to 404s in this repo. 

![image](https://github.com/google-gemini/cookbook/assets/69743171/46c35c2a-8c65-44e7-b314-8cdaeb3e682f)

**Comment by singhniraj08** [comment]
@quick007, The links to all tutorials have been fixed in [Gemini API CookBook](https://ai.google.dev/gemini-api/cookbook) page. Please try out and let us know if you face any issues. Thank you!

**Comment by quick007** [comment]
@singhniraj08 Seems to be fixed, thanks!
