### ISSUE TITLE
https://github.com/google-gemini/cookbook/blob/main/quickstarts/File_API.ipynb gives error when loading

### ISSUE THREAD

**Issue by logankilpatrick** [google-gemini/cookbook#153]
### Description of the bug:

https://github.com/google-gemini/cookbook/blob/main/quickstarts/File_API.ipynb currently does not load on GitHub

### Actual vs expected behavior:

I expect it to load

**Comment by markmcd** [comment]
Looks like GitHub: https://github.com/orgs/community/discussions/124651

Not much we can do :(
