### ISSUE TITLE
Cookbook: "Code examples" links needs to be updated

### ISSUE THREAD

**Issue by pratikbutani** [google-gemini/cookbook#155]
### Description of the bug:

I've just checked the cookbook links and found few links are dead in [below area:](https://ai.google.dev/gemini-api/cookbook)

<img width="1636" alt="Screenshot 2024-05-20 at 5 42 01 PM" src="https://github.com/google-gemini/cookbook/assets/3306366/37764598-ca63-41ad-8f71-f3a9f28eb007">

### Actual vs expected behavior:

The link for first card "Anomaly Detection" having [this wrong link](https://github.com/google-gemini/cookbook/blob/main/cookbook/Anomaly_detection_with_embeddings.ipynb) instead of [this correct link](https://github.com/google-gemini/cookbook/blob/main/examples/Anomaly_detection_with_embeddings.ipynb)

Same way all the card under the **Code examples** section having same issue. 
All the links should be 

`main/examples/<FileName>.ipynb`

instead of 

`main/cookbook/<FileName>.ipynb`

**Comment by markmcd** [comment]
Should be fixed now. Thanks for the report.

**Comment by pratikbutani** [comment]
> Should be fixed now. Thanks for the report.

Most welcome, Glad to help :)
