### ISSUE TITLE
in Audio.ipyn count_tokens results in 403

### ISSUE THREAD

**Issue by ahmetkizilay** [google-gemini/cookbook#175]
### Description of the bug:

Running the [Audio.ipyn](https://github.com/google-gemini/cookbook/blob/main/quickstarts/Audio.ipynb) file, I am getting 403 error when running the count_tokens step.

You do not have permission to access the File m7gxa43f7pft or it may not exist.

To replicate, 
1 - Open the notebook in Google Colab,
2 - Setup the GOOGLE_API_KEY
3 - run all commands

### Actual vs expected behavior:

actual behavior: `model.count_tokens([your_file])` returns error

I expect all steps in the cookbook execute without errors.

**Comment by singhniraj08** [comment]
Running `model.count_tokens([your_file])` returns file permission access error.

![image](https://github.com/google-gemini/cookbook/assets/110809167/7273c19a-217c-4f15-9d1e-8d0004d5d222)

**Comment by lucianommartins** [comment]
Hi @ahmetkizilay - I've just run `Audio.ipynb` on a Colab session and everything worked fine up to the `model.count_tokens([your_file])` cell.

I noticed on your error message that you are using `gemini-1.0-pro` which is not the model used on the current notebook version.

Could you experiment with the latest version of this notebook and double check if the error persists for you? 

cheers,
Luciano Martins.

**Comment by ahmetkizilay** [comment]
This seems to be resolved (even with the older model).

```
model = genai.GenerativeModel("models/gemini-1.0-pro")
model.count_tokens([uploaded_sample])
```

returns without an error
