### ISSUE TITLE
A small spelling mistake

### ISSUE THREAD

**Issue by zijin2** [google-gemini/cookbook#184]
### Description of the bug:

Paragraph above "Manual function calling" part, the word "Iff" shoud be "If".

**Comment by singhniraj08** [comment]
@linsong8208, Thank you for reporting this issue. Please do let us know the document or tutorial you are referring to with the typo. We would be happy to fix it or if you are interested in contributing for the fix, feel free to create a PR. Thank you!

**Comment by linsong8208** [comment]
hi singhniraj08, already handed in PR.

**Comment by markmcd** [comment]
Sounds like this is already done.
