### ISSUE TITLE
Sherlock_Jr.ipynb was removed

### ISSUE THREAD

**Issue by sociengineer** [google-gemini/cookbook#203]
### Description of the bug:

Hi team,
I recently checked that Sherlock_Jr.ipynb was removed in the examples.

### Actual vs expected behavior:

Sherlock_Jr.ipynb does exists in the examples

**Comment by markmcd** [comment]
Looks like it was deleted in f8c866fba7bacd650c85fd345a6e39bf849cf5f3, so you can find it at the previous commit, e.g. [Sherlock_Jr.ipynb](https://github.com/google-gemini/cookbook/blob/590096b95936d2991e27e6d4dfc573f30f073ec0/examples/Sherlock_Jr.ipynb)

There's nothing in the commit that indicates why it was removed, but @lucianommartins might be able to help.

**Comment by MarkDaoust** [comment]
This example totally stopped working.

luciano reported this to the api team and deleted in the mean time. He deleted it because It seemed like a negative to have it sitting here, broken. Why the interest?

**Comment by sociengineer** [comment]
I see. I just wanted to change this asset to make a demo. My demo summarizes a video clip focusing on a person in the video. I'll find another way to implement this idea. Thank you :)
