### ISSUE TITLE
How to fine tune the model with images?

### ISSUE THREAD

**Issue by Iven2132** [google-gemini/cookbook#235]
### Description of the feature request:

How to fine tune the model with images? fine-tune

### What problem are you trying to solve with this feature?

fine-tune the multimodal

**Comment by romankulkovsf** [comment]
Hey
I have problem with payment

**Comment by markmcd** [comment]
The underlying tuning feature does not currently support using images - only text. There's not much we can do about that in the cookbook unfortunately so I'll close this.

I recommend that anyone interested in this feature should file feedback through AI Studio, using `Send feedback` under the `⋮` menu.

**Comment by praz88** [comment]
Looks like it's supported now

https://cloud.google.com/vertex-ai/generative-ai/docs/models/tune_gemini/image_tune
