### ISSUE TITLE
Missing OpenAPI spec

### ISSUE THREAD

**Issue by KotlinFactory** [google-gemini/cookbook#261]
### Description of the feature request:

We need an OpenAPI spec for the gemini API. 
The SpringAI team or some contributors would use this to implement Google Gemini directly into SpringAI. However this is not possible without reverse engineering code of existing clients like the python clients. (Which I would love not having to do)

See: https://github.com/spring-projects/spring-ai/issues/1252

### What problem are you trying to solve with this feature?

Google Gemini should be available for the server side Java/JVM world.

**Comment by markmcd** [comment]
We don't use OpenAPI specs for our APIs, we use protocol buffer specs that are converted to [discovery documents](https://developers.google.com/discovery/v1/reference/apis) for, e.g. auto-generated client libraries.

Here's the [service definition in proto format](https://github.com/googleapis/googleapis/blob/master/google/ai/generativelanguage/v1beta/generative_service.proto), and here's the [discovery URL](https://generativelanguage.googleapis.com/\$discovery/rest?version=v1beta&key=$GOOGLE_API_KEY) (make sure you substitute your API key)

I believe we can turn OpenAPI output on but I'd need to look into what trade-offs/compatibility issues there are, if any.

Have you tried using a converter? e.g. [gnostic](https://github.com/google/gnostic) will generate openapi from the proto def, and there are other tools that do discovery -> openapi, as well as [catalogues of converted API specs](https://github.com/APIs-guru/openapi-directory/tree/main/APIs/googleapis.com).

**Comment by markmcd** [comment]
FYI - we have now published an OpenAPI spec on the API:

https://generativelanguage.googleapis.com/$discovery/OPENAPI3_0?version=v1beta&key=$GOOGLE_API_KEY

e.g.

```sh
curl "https://generativelanguage.googleapis.com/\$discovery/OPENAPI3_0?version=v1beta&key=$GOOGLE_API_KEY" |jq '.paths |keys'
```

**Comment by davidxia** [comment]
@markmcd Thanks, is there a way to access the spec without an API key? I want to embed the spec into my own OpenAPI spec which requires referencing the URL. But I don't want to commit an OpenAPI YAML file with a sensitive key into VCS.

**Comment by rib** [comment]
It would be great if this was also documented as part of the Gemini Developer API docs, not only buried within a "Not planned" Github issue.

I agree with @davidxia that it would also be convenient if it didn't require an API key to fetch this spec.

**Comment by bit-factor** [comment]
> FYI - we have now published an OpenAPI spec for the API. This might help folks over in [spring-projects/spring-ai#1252](https://github.com/spring-projects/spring-ai/issues/1252)
> 
> https://generativelanguage.googleapis.com/$discovery/OPENAPI3_0?version=v1beta&key=$GOOGLE_API_KEY
> 
> e.g.
> 
> curl "https://generativelanguage.googleapis.com/\$discovery/OPENAPI3_0?version=v1beta&key=$GOOGLE_API_KEY" |jq '.paths |keys'

It would be awesome to be able to get the definition without the api-key. In the end, this definition is nothing but the documentation of the service ...

**Comment by markmcd** [comment]
Thanks for the request - I've fixed it for ya.

You can get to https://generativelanguage.googleapis.com/$discovery/rest?version=v1beta and https://generativelanguage.googleapis.com/$discovery/OPENAPI3_0?version=v1beta now without an API key.
