### ISSUE TITLE
TypeError: argument of type 'Part' is not iterable

### ISSUE THREAD

**Issue by Trishanu123** [google-gemini/cookbook#274]
### Description of the bug:

I am getting a error of "Part" when i try running the code. 

### Actual vs expected behavior:

import google.generativeai as genai
import os

genai.configure(api_key=os.environ["API_KEY"])
model = genai.GenerativeModel('gemini-1.0-pro-latest')
response = model.generate_content("The opposite of hot is")
print(response.text)

Above is the code I am trying to run. But it's throwing me a error "TypeError: argument of type 'Part' is not iterable"

**Comment by gmKeshari** [comment]
Hi @Trishanu123. I replicated the same code in colab, it is not throwing any error. Can you try the notebook below (Save your api in colab secrets as "GeminiAPI") :

https://colab.sandbox.google.com/gist/gmKeshari/098b50f1c17fc794e05541d2d9e7c8a7/try_errors.ipynb

Also, I tried with your exact same code, it's working. If it's not working for you then try to upgrade google-generativeai using below command :

pip install --upgrade google-generativeai

Hope, this will resolve your issue.

**Comment by Alexisloyolamend3z** [comment]
Hola
