### ISSUE TITLE
Question: Forms of contribution

### ISSUE THREAD

**Issue by NSTiwari** [google-gemini/cookbook#30]
I have a couple of questions.

- Does this repository currently accept examples only in the form of Colab notebooks? Are end-to-end project applications acceptable? For example: [PharmaScan](https://github.com/NSTiwari/Medicine-Scan-with-Gemini) is an Android app that leverages Gemini Pro Vision model to identify medicines and provide their details such as usage, dosage, diagnosis, etc. on-the-go.

- Can Gemma projects be submitted as well? If no, do we have a separate repository for that?

**Comment by NSTiwari** [comment]
@markmcd: Could you please with this?

**Comment by markmcd** [comment]
> only in the form of Colab notebooks

This is true. We now mention this in CONTRIBUTING.md.

> Can Gemma projects be submitted as well? 

We now have t he Gemma Cookbook for Gemma related content: https://github.com/google-gemini/gemma-cookbook
