### ISSUE TITLE
need go sdk for live audio chat? 

### ISSUE THREAD

**Issue by vizvasrj** [google-gemini/cookbook#337]
### Description of the feature request:

could you please provide me go lang code for this? `gemini-2/live_api_starter.py`

### What problem are you trying to solve with this feature?

i have been trying to use `go-genai/samples/generate_audio.go` but it does not work 
from https://github.com/googleapis/go-genai/blob/main/samples/generate_audio.go

### Any other information you'd like to share?

Thnk you.

**Comment by markmcd** [comment]
If you have any issues with the code in that repository, you will want to file an issue in that repository.

We don't host any Go code over here, though maybe we could cross-link to the various SDK sample directories from our README(s). I'll close this but if anyone wants to send a PR to do that, feel free.
