### ISSUE TITLE
Bounding box detection error (Gemini 2.0 (experimental) API)

### ISSUE THREAD

**Issue by Soclatos** [google-gemini/cookbook#345]
### Description of the bug:

I used the latest Gemini 2.0 (experimental) API for image recognition. My test image is a matrix of letters, but the results returned and the visualization do not match. The bounding boxes do not correctly correspond to the letter positions.
I used the same code as https://github.com/google-gemini/cookbook/blob/main/gemini-2/spatial_understanding.ipynb, and the result is shown in the image.
I also tried other visualization methods, modified the code myself, but it still didn't work.
I also used Google AI Studio's Starter Apps for testing and encountered the same issue.
So I'm not sure if there's an issue with the normalized coordinates returned by the API.

![test7](https://github.com/user-attachments/assets/ea7bacca-6647-4167-8ac3-6a432886319b)
![result_googleaitest](https://github.com/user-attachments/assets/11814626-7a87-4904-a6bf-796ca2b4a8f2)
<img width="1269" alt="Snipaste_2024-12-12_21-21-56" src="https://github.com/user-attachments/assets/dfb24b9b-547f-4b67-8041-203f6826cfc3" />

**Comment by Giom-V** [comment]
Hello @Soclatos,

Thanks for reporting your experience. It's kind of a known issue when there are too many things to detect that Gemini sometimes gets the coordinates wrong. We'll flagged it to the Deepmind team and they're working at making it more robust in future models.

The only advice I can give you is to try with dedicated system instructions. I could help the model.

**Comment by Soclatos** [comment]
> Hello @Soclatos,
> 
> Thanks for reporting your experience. It's kind of a known issue when there are too many things to detect that Gemini sometimes gets the coordinates wrong. We'll flagged it to the Deepmind team and they're working at making it more robust in future models.
> 
> The only advice I can give you is to try with dedicated system instructions. I could help the model.

Thanks to your reply. Looking forward to a more robust model.
