### ISSUE TITLE
Grounding requirements hosted on google internal webpage (hence not accessible)

### ISSUE THREAD

**Issue by hamonk** [google-gemini/cookbook#346]
### Description of the bug:

In the https://github.com/google-gemini/cookbook/blob/main/quickstarts/Search_Grounding.ipynb notebook, it says:

Important: If you use search grounding you must follow the [requirements outlined here](https://googledevai.devsite.corp.google.com/gemini-api/docs/grounding/search-suggestions?hl=en#requirements)

That https://googledevai.devsite.corp.google.com website is not public so I can't see what the search grounding requirements are.

### Actual vs expected behavior:

The requirements should be on a website accessible by anybody.

When I go to https://googledevai.devsite.corp.google.com/gemini-api/docs/grounding/search-suggestions?hl=en#requirements it is asking for Google credentials

**Comment by markmcd** [comment]
Thanks for spotting that. I have a PR in #347 that fixes the URL, but while you are waiting for that, anything that says `googledevai.devsite.corp.google.com` can be replaced with `ai.google.dev` and it will work.
