### ISSUE TITLE
live_api_starter.ipynb has link "Live API Audio Video to Audio python script" that points to non existing github page "https://github.com/google-gemini/cookbook/blob/main/gemini-2/websockets/live_api_audio_video_to_audio.py"

### ISSUE THREAD

**Issue by ViaAnthroposBenevolentia** [google-gemini/cookbook#350]
### Description of the bug:

![image](https://github.com/user-attachments/assets/3a87e690-40ad-43b4-a12a-24d8b94e5dfc)
![image](https://github.com/user-attachments/assets/25b63283-b530-4f33-82bc-f3df2067c1e9)
![image](https://github.com/user-attachments/assets/c425a826-493a-428b-8c5f-70597739bdc8)
I wanted to see an Audio and Video streaming guide by following the link, but it seems the file was deleted. Just letting you know!

### Actual vs expected behavior:

Got: 404 non existing github file page
Expected: Example file to use Gemini Multimodal API to send Video&Audio to get Audio Realtime Feedback

**Comment by Giom-V** [comment]
@ViaAnthroposBenevolentia, I think the script it should points to is https://github.com/google-gemini/cookbook/blob/main/gemini-2/websockets/live_api_starter.py but since I'm not 100% certain I'll let the Marks confirm and fix the notebook.

**Comment by ViaAnthroposBenevolentia** [comment]
Hi! [logankilpatrick](https://github.com/logankilpatrick) had updated that notebook with #349, so I guess I can close this?
