### ISSUE TITLE
TimeoutError: timed out during handshake

### ISSUE THREAD

**Issue by SeanFeng91** [google-gemini/cookbook#384]
### Description of the bug:

Problem:

The code works fine when running in Colab, but when I try to run it locally in my country, I keep encountering the TimeoutError: timed out during handshake issue. I've already tried using a VPN, but I still can't access WebSockets properly.

Does anyone have any good solutions to fix this?

Thank You!

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In[7], [line 1](vscode-notebook-cell:?execution_count=7&line=1)
----> [1](vscode-notebook-cell:?execution_count=7&line=1) await run(prompt='Hello?')

Cell In[6], [line 66](vscode-notebook-cell:?execution_count=6&line=66)
     [63](vscode-notebook-cell:?execution_count=6&line=63) if tools is None:
     [64](vscode-notebook-cell:?execution_count=6&line=64)   tools=[]
---> [66](vscode-notebook-cell:?execution_count=6&line=66) async with (
     [67](vscode-notebook-cell:?execution_count=6&line=67)     connect(uri, additional_headers={"Content-Type": "application/json"}) as ws,
     [68](vscode-notebook-cell:?execution_count=6&line=68) ):
     [69](vscode-notebook-cell:?execution_count=6&line=69)   await setup(ws, modality, tools)
     [70](vscode-notebook-cell:?execution_count=6&line=70)   await send(ws, prompt)

File c:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\websockets\asyncio\client.py:485, in connect.__aenter__(self)
    [484](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:484) async def __aenter__(self) -> ClientConnection:
--> [485](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:485)     return await self

File c:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\websockets\asyncio\client.py:476, in connect.__await_impl__(self)
    [472](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:472)             raise SecurityError(f"more than {MAX_REDIRECTS} redirects")
    [474](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:474) except TimeoutError:
    [475](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:475)     # Re-raise exception with an informative error message.
--> [476](file:///C:/Users/maoxi/github/miniconda3/envs/finance_bot/Lib/site-packages/websockets/asyncio/client.py:476)     raise TimeoutError("timed out during handshake") from None

TimeoutError: timed out during handshake

**Comment by cdliufei** [comment]
met the same error here. waiting for the response

**Comment by Usgupta** [comment]
+1

**Comment by sonald** [comment]
+1

**Comment by Giom-V** [comment]
From which country are you trying to use Gemini?
Can you run `!curl ipinfo.io`?

**Comment by SeanFeng91** [comment]
China, but now I can get access somehow. I am trying to figure out why

**Comment by chadshao** [comment]
> China, but now I can get access somehow. I am trying to figure out why

How was it solved?

**Comment by SeanFeng91** [comment]
> > China, but now I can get access somehow. I am trying to figure out why
> 
> How was it solved?

I try to use websocket instead of websockets in my vitepress blog. This may be the reason?


```
// 运行对话
const run = async (prompt, modality = 'TEXT', tools = []) => {
  return new Promise((resolve, reject) => {
    const uri = `wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContent?key=${import.meta.env.VITE_GEMINI_API_KEY}`
    
    try {
      ws = new WebSocket(uri)
      ws.addEventListener('open', async () => {
        try {
          await setup(ws, modality, tools)
          await send(ws, prompt)
        } catch (error) {
          reject(error)
        }
      })

      ws.addEventListener('message', async (event) => {
        try {
          let response
          if (event.data instanceof Blob) {
            const text = await event.data.text()
            response = JSON.parse(text)
          } else {
            response = JSON.parse(event.data)
          }
          
          logger.value?.debug('收到消息:', response)

          const serverContent = response.serverContent
          if (serverContent) {
            const [turnComplete, audio] = handleServerContent(serverContent)
            if (turnComplete) {
              resolve()
              return
            }
          }

          const toolCall = response.toolCall
          if (toolCall) {
            await handleToolCall(ws, toolCall)
          }
        } catch (error) {
          logger.value?.error('消息处理错误:', error)
        }
      })

      ws.addEventListener('error', (error) => {
        logger.value?.error('WebSocket 错误:', error)
        reject(error)
      })

      ws.addEventListener('close', () => {
        logger.value?.debug('WebSocket 已关闭')
        resolve()
      })
    } catch (error) {
      reject(error)
    }
  })
}
```

**Comment by Giom-V** [comment]
Gemini is not available in China (cf. https://ai.google.dev/gemini-api/docs/available-regions#available_regions), so that's your issue.

**Comment by NightMachinery** [comment]
How do I check if the timeout is because of a region block or sth else? I am trying to connect to the API from a UK VPS, but it times out.
