### ISSUE TITLE
File API does not delete files upon request

### ISSUE THREAD

**Issue by yp583** [google-gemini/cookbook#62]
genai.delete_file(frame.response.name), buffers forever. There is no response, no error, just buffering until I cancel the call.

**Comment by yp583** [comment]
I'm using Python, and its a local file (just a .py), not a notebook.

**Comment by TYMichaelChen** [comment]
Thanks! Is it possible to share the code with me so I can debug further?

**Comment by yp583** [comment]
Sorry, I'm not sure I still have it. I will try and find it for you though.

**Comment by MarkDaoust** [comment]
The example's working fine in colab, I don't think we can help without sone way to reproduce this.

**Comment by jochenkirstaetter** [comment]
Deleting files via REST API also works fine. Using the provided `files/sjkdfsdi` name to delete it. The name can be retrieved using the `list_files` method.

I used this approach in my Gemini SDK for .NET. Works nicely.
