### ISSUE TITLE
Streaming Quickstart: Must be run locally, but first item in notebook is a button to run it in Colab

### ISSUE THREAD

**Issue by gaborcselle** [google-gemini/cookbook#67]
The [https://github.com/google-gemini/cookbook/blob/cf2dc7a3a851c5f553c2bf9ff884770719ca368d/quickstarts/Streaming.ipynb](`quickstarts/Streaming.ipynb`) notebook says at the top to Download it and run it locally, as streaming is not correctly handled in Colab yet.

I recommend removing this button as it can confuse users - they'll spin up the notebook in Colab where it doesn't work.

**Comment by MarkDaoust** [comment]
Fixed.
