### ISSUE TITLE
[Run in Google Colab] An exception occurred User location is not supported for the API use

### ISSUE THREAD

**Issue by maxuechaogao** [google-gemini/cookbook#72]
Hello, according to the example  https://github.com/google-gemini/cookbook/blob/main/quickstarts/Video.ipynb，Run in Google Colab Execution, the following error occurred， ![image](https://github.com/google-gemini/cookbook/assets/29362988/fbdb2a92-1f9a-4f58-8d99-7fa7265298ab)
![image](https://github.com/google-gemini/cookbook/assets/29362988/98450bab-df5b-41e3-8f00-15ce8d15b696)

**Comment by markmcd** [comment]
Are you running from an [available region](https://ai.google.dev/available_regions)?

**Comment by maxuechaogao** [comment]
> Are you running from an [available region](https://ai.google.dev/available_regions)?

After logging into my Google account, it was automatically assigned to me and I did not actively select any nodes

**Comment by williamito** [comment]
Unfortunately there's no way to force where Colab runtimes are created. Try deleting your runtime and creating a new one to have it pick a region again. You can use `!curl ipinfo.io` to see where your session is located.
