### ISSUE TITLE
Gemini API: Prompting with Video - genai.upload_file [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by maxuechaogao** [google-gemini/cookbook#73]
![image](https://github.com/google-gemini/cookbook/assets/29362988/3c71cbab-2b5a-4f51-bb36-7bb1b3cb8c0c)
![image](https://github.com/google-gemini/cookbook/assets/29362988/113827ac-7b32-4da1-865c-f11724212a66)

**Comment by maxuechaogao** [comment]
How should I handle it so that I can execute the function to upload files locally? Additionally, what does this function correspond to 【POST https://generativelanguage.googleapis.com/upload/v1beta/files】？

**Comment by TYMichaelChen** [comment]
Hi, are you running this in an [available region](https://ai.google.dev/available_regions) by the way?  Seems like this might be related to the other issue: https://github.com/google-gemini/cookbook/issues/72

**Comment by maxuechaogao** [comment]
> Hi, are you running this in an [available region](https://ai.google.dev/available_regions) by the way? Seems like this might be related to the other issue: #72
Yes, I am using a US node

**Comment by garmanwu** [comment]
the same proble,genai.upload_file time out.

**Comment by garmanwu** [comment]
I find the solution.

Make sure Audio.ipynb works fine. That means the server end is OK.
https://colab.research.google.com/github/google-gemini/cookbook/blob/main/quickstarts/Audio.ipynb

The error happens in the network connection even you change the VPN node. You can set python code as below:
os.environ['http_proxy']='http://127.0.0.1:7890'
os.environ['https_proxy']='http://127.0.0.1:7890'
os.environ['all_proxy']='sock5://127.0.0.1:7890'
genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

It works fine for me. Good luck~

**Comment by maxuechaogao** [comment]
> I find the solution.
> 
> Make sure Audio.ipynb works fine. That means the server end is OK. https://colab.research.google.com/github/google-gemini/cookbook/blob/main/quickstarts/Audio.ipynb
> 
> The error happens in the network connection even you change the VPN node. You can set python code as below: os.environ['http_proxy']='http://127.0.0.1:7890' os.environ['https_proxy']='http://127.0.0.1:7890' os.environ['all_proxy']='sock5://127.0.0.1:7890' genai.configure(api_key=GOOGLE_API_KEY,transport='rest')
> 
> It works fine for me. Good luck~

Thank you very much. This configuration is indeed feasible

**Comment by wangy325** [comment]
> I find the solution.
> 
> Make sure Audio.ipynb works fine. That means the server end is OK. https://colab.research.google.com/github/google-gemini/cookbook/blob/main/quickstarts/Audio.ipynb
> 
> The error happens in the network connection even you change the VPN node. You can set python code as below: os.environ['http_proxy']='http://127.0.0.1:7890' os.environ['https_proxy']='http://127.0.0.1:7890' os.environ['all_proxy']='socks5://127.0.0.1:7890' genai.configure(api_key=GOOGLE_API_KEY,transport='rest')
> 
> It works fine for me. Good luck~

Works for me. thx a lot 😀 By the way, genai is not supported in HongKong, that's sad😅
