### ISSUE TITLE
Real time data like gemini.google.com/

### ISSUE THREAD

**Issue by tomnewg** [google-gemini/cookbook#90]
For some reason the model I use only has data until the date it was trained and is not searching the internet for current information such as gemini.google.com/ is doing it. 
I tried:
genai.GenerativeModel('gemini-pro')
genai.GenerativeModel('gemini-1.0-pro-latest')
genai.GenerativeModel('gemini-1.5-pro-latest')

is there a different model to be used? or some other setting or not possible yet?

Many thanks

Tom

**Comment by keertk** [comment]
Hi @tomnewg thanks for the questions! Correct, the models are currently not searching the internet and only use data until the date they were trained. There's no setting or other alternative at present.

For general questions and discussions around Google AI, please check out our [Discourse forum](https://discuss.ai.google.dev/).
